### ISSUE TITLE
To-Do List for Group 3 Final Labs

### ISSUE THREAD

**Issue by 3osmic** [CbarNC/Group3-repo-projects#24]
Developers --
- [ ] Condense flask folder
- [ ] Make a separate folder for all html images

Document Writers --
- [ ] Put all screenshots and videos in one folder
